version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: Worker
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_MEMORY: 400m
    SPARK_MASTER_URL: spark://spark-master:7077
  networks:
    - oussamaNetwork

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181" # Mapping container port 2181 to host port 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ['CMD', 'BASH ', '-c' , "echo 'ruok' | nc localhost 2181"]
      interval: 30s 
      timeout: 15s
      retries: 10
    networks:
      - oussamaNetwork

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    depends_on:
      zookeeper:
        condition: service_healthy # Waiting for zookeeper
    ports:
      - "9092:9092" # Kafka broker port
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092 # We use to connect with the broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Number or replications
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENCE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Depending on connecting to zookeeper
      CONFLUENT_METRICS_ENABLE: 'false' # We are not enabling any metrics
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous' 
      KAFKA_LOG_RETENTION_MS: 604800000 # 7 days 
    healthcheck:
      test: ['CMD', 'BASH ', '-c' , "echo 'ruok' | nc localhost 2181"]
      interval: 20s 
      timeout: 10s
      retries: 7
    networks:
      - oussamaNetwork

  spark-master:
    image: bitnami/spark:latest
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - oussamaNetwork

  spark-worker-1:
    <<: *spark-common

  spark-worker-2:
    <<: *spark-common

networks:
  oussamaNetwork:
    driver: bridge
